---
# handlers file for install-check_mk-client
- name: Restart Windows agent service
  win_service:
    name: CheckMKService
    state: restarted
  tags:
    - install-check-mk-client
    - files
...
